@host = http://localhost:5056
@trueToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjJhOGY2Mi02NDI4LTRmMWItYmE2Yi03NTNlZjllMTg4OTAiLCJnaXZlbl9uYW1lIjoiQmFvIiwiZmFtaWx5X25hbWUiOiJOUSIsImp0aSI6ImE4NzI3NTkyLWRmNDMtNGM5Zi1iMWExLTNlMDNiYzNhNTQ0YiIsImV4cCI6MTcxMDQ5NTIzMSwiaXNzIjoiQmFvIE5RIiwiYXVkIjoiTG9raSBMQVVGRVlTT04ifQ.IlNdEfrtr6Ool43s_-1wcxkFoDpOwJj6gw2ysP_bNiY

@falseToken = ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjJhOGY2Mi02NDI4LTRmMWItYmE2Yi03NTNlZjllMTg4OTAiLCJnaXZlbl9uYW1lIjoiQmFvIiwiZmFtaWx5X25hbWUiOiJOUSIsImp0aSI6ImE4NzI3NTkyLWRmNDMtNGM5Zi1iMWExLTNlMDNiYzNhNTQ0YiIsImV4cCI6MTcxMDQ5NTIzMSwiaXNzIjoiQmFvIE5RIiwiYXVkIjoiTG9raSBMQVVGRVlTT04ifQ.IlNdEfrtr6Ool43s_-1wcxkFoDpOwJj6gw2ysP_bNiY

GET {{host}}/rendezvous/
Content-Type: application/json
Authorization: Bearer {{trueToken}}